//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.TPEduInfoTransferSoap")]
    public interface TPEduInfoTransferSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        TestWeb.ServiceReference1.HelloWorldResponse HelloWorld(TestWeb.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWeb.ServiceReference1.HelloWorldResponse> HelloWorldAsync(TestWeb.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetECertInfo", ReplyAction="*")]
        TestWeb.ServiceReference1.GetECertInfoResponse GetECertInfo(TestWeb.ServiceReference1.GetECertInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetECertInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWeb.ServiceReference1.GetECertInfoResponse> GetECertInfoAsync(TestWeb.ServiceReference1.GetECertInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 XTID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendContinueEdu", ReplyAction="*")]
        TestWeb.ServiceReference1.SendContinueEduResponse SendContinueEdu(TestWeb.ServiceReference1.SendContinueEduRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendContinueEdu", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWeb.ServiceReference1.SendContinueEduResponse> SendContinueEduAsync(TestWeb.ServiceReference1.SendContinueEduRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetailsBrower", ReplyAction="*")]
        TestWeb.ServiceReference1.DetailsBrowerResponse DetailsBrower(TestWeb.ServiceReference1.DetailsBrowerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetailsBrower", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWeb.ServiceReference1.DetailsBrowerResponse> DetailsBrowerAsync(TestWeb.ServiceReference1.DetailsBrowerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public TestWeb.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(TestWeb.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestWeb.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(TestWeb.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetECertInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetECertInfo", Namespace="http://tempuri.org/", Order=0)]
        public TestWeb.ServiceReference1.GetECertInfoRequestBody Body;
        
        public GetECertInfoRequest() {
        }
        
        public GetECertInfoRequest(TestWeb.ServiceReference1.GetECertInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetECertInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XTID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SFZH;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string XM;
        
        public GetECertInfoRequestBody() {
        }
        
        public GetECertInfoRequestBody(string XTID, string SFZH, string XM) {
            this.XTID = XTID;
            this.SFZH = SFZH;
            this.XM = XM;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetECertInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetECertInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestWeb.ServiceReference1.GetECertInfoResponseBody Body;
        
        public GetECertInfoResponse() {
        }
        
        public GetECertInfoResponse(TestWeb.ServiceReference1.GetECertInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetECertInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetECertInfoResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OUTINFO;
        
        public GetECertInfoResponseBody() {
        }
        
        public GetECertInfoResponseBody(string GetECertInfoResult, string OUTINFO) {
            this.GetECertInfoResult = GetECertInfoResult;
            this.OUTINFO = OUTINFO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendContinueEduRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendContinueEdu", Namespace="http://tempuri.org/", Order=0)]
        public TestWeb.ServiceReference1.SendContinueEduRequestBody Body;
        
        public SendContinueEduRequest() {
        }
        
        public SendContinueEduRequest(TestWeb.ServiceReference1.SendContinueEduRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendContinueEduRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XTID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string JYXX;
        
        public SendContinueEduRequestBody() {
        }
        
        public SendContinueEduRequestBody(string XTID, string JYXX) {
            this.XTID = XTID;
            this.JYXX = JYXX;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendContinueEduResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendContinueEduResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestWeb.ServiceReference1.SendContinueEduResponseBody Body;
        
        public SendContinueEduResponse() {
        }
        
        public SendContinueEduResponse(TestWeb.ServiceReference1.SendContinueEduResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendContinueEduResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendContinueEduResult;
        
        public SendContinueEduResponseBody() {
        }
        
        public SendContinueEduResponseBody(string SendContinueEduResult) {
            this.SendContinueEduResult = SendContinueEduResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DetailsBrowerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DetailsBrower", Namespace="http://tempuri.org/", Order=0)]
        public TestWeb.ServiceReference1.DetailsBrowerRequestBody Body;
        
        public DetailsBrowerRequest() {
        }
        
        public DetailsBrowerRequest(TestWeb.ServiceReference1.DetailsBrowerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DetailsBrowerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fkey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string StrWebUrl;
        
        public DetailsBrowerRequestBody() {
        }
        
        public DetailsBrowerRequestBody(string fkey, string StrWebUrl) {
            this.fkey = fkey;
            this.StrWebUrl = StrWebUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DetailsBrowerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DetailsBrowerResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestWeb.ServiceReference1.DetailsBrowerResponseBody Body;
        
        public DetailsBrowerResponse() {
        }
        
        public DetailsBrowerResponse(TestWeb.ServiceReference1.DetailsBrowerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DetailsBrowerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DetailsBrowerResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OUTINFO;
        
        public DetailsBrowerResponseBody() {
        }
        
        public DetailsBrowerResponseBody(string DetailsBrowerResult, string OUTINFO) {
            this.DetailsBrowerResult = DetailsBrowerResult;
            this.OUTINFO = OUTINFO;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TPEduInfoTransferSoapChannel : TestWeb.ServiceReference1.TPEduInfoTransferSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TPEduInfoTransferSoapClient : System.ServiceModel.ClientBase<TestWeb.ServiceReference1.TPEduInfoTransferSoap>, TestWeb.ServiceReference1.TPEduInfoTransferSoap {
        
        public TPEduInfoTransferSoapClient() {
        }
        
        public TPEduInfoTransferSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TPEduInfoTransferSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TPEduInfoTransferSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TPEduInfoTransferSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWeb.ServiceReference1.HelloWorldResponse TestWeb.ServiceReference1.TPEduInfoTransferSoap.HelloWorld(TestWeb.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            TestWeb.ServiceReference1.HelloWorldRequest inValue = new TestWeb.ServiceReference1.HelloWorldRequest();
            inValue.Body = new TestWeb.ServiceReference1.HelloWorldRequestBody();
            TestWeb.ServiceReference1.HelloWorldResponse retVal = ((TestWeb.ServiceReference1.TPEduInfoTransferSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWeb.ServiceReference1.HelloWorldResponse> TestWeb.ServiceReference1.TPEduInfoTransferSoap.HelloWorldAsync(TestWeb.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWeb.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            TestWeb.ServiceReference1.HelloWorldRequest inValue = new TestWeb.ServiceReference1.HelloWorldRequest();
            inValue.Body = new TestWeb.ServiceReference1.HelloWorldRequestBody();
            return ((TestWeb.ServiceReference1.TPEduInfoTransferSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWeb.ServiceReference1.GetECertInfoResponse TestWeb.ServiceReference1.TPEduInfoTransferSoap.GetECertInfo(TestWeb.ServiceReference1.GetECertInfoRequest request) {
            return base.Channel.GetECertInfo(request);
        }
        
        public string GetECertInfo(string XTID, string SFZH, string XM, out string OUTINFO) {
            TestWeb.ServiceReference1.GetECertInfoRequest inValue = new TestWeb.ServiceReference1.GetECertInfoRequest();
            inValue.Body = new TestWeb.ServiceReference1.GetECertInfoRequestBody();
            inValue.Body.XTID = XTID;
            inValue.Body.SFZH = SFZH;
            inValue.Body.XM = XM;
            TestWeb.ServiceReference1.GetECertInfoResponse retVal = ((TestWeb.ServiceReference1.TPEduInfoTransferSoap)(this)).GetECertInfo(inValue);
            OUTINFO = retVal.Body.OUTINFO;
            return retVal.Body.GetECertInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWeb.ServiceReference1.GetECertInfoResponse> TestWeb.ServiceReference1.TPEduInfoTransferSoap.GetECertInfoAsync(TestWeb.ServiceReference1.GetECertInfoRequest request) {
            return base.Channel.GetECertInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWeb.ServiceReference1.GetECertInfoResponse> GetECertInfoAsync(string XTID, string SFZH, string XM) {
            TestWeb.ServiceReference1.GetECertInfoRequest inValue = new TestWeb.ServiceReference1.GetECertInfoRequest();
            inValue.Body = new TestWeb.ServiceReference1.GetECertInfoRequestBody();
            inValue.Body.XTID = XTID;
            inValue.Body.SFZH = SFZH;
            inValue.Body.XM = XM;
            return ((TestWeb.ServiceReference1.TPEduInfoTransferSoap)(this)).GetECertInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWeb.ServiceReference1.SendContinueEduResponse TestWeb.ServiceReference1.TPEduInfoTransferSoap.SendContinueEdu(TestWeb.ServiceReference1.SendContinueEduRequest request) {
            return base.Channel.SendContinueEdu(request);
        }
        
        public string SendContinueEdu(string XTID, string JYXX) {
            TestWeb.ServiceReference1.SendContinueEduRequest inValue = new TestWeb.ServiceReference1.SendContinueEduRequest();
            inValue.Body = new TestWeb.ServiceReference1.SendContinueEduRequestBody();
            inValue.Body.XTID = XTID;
            inValue.Body.JYXX = JYXX;
            TestWeb.ServiceReference1.SendContinueEduResponse retVal = ((TestWeb.ServiceReference1.TPEduInfoTransferSoap)(this)).SendContinueEdu(inValue);
            return retVal.Body.SendContinueEduResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWeb.ServiceReference1.SendContinueEduResponse> TestWeb.ServiceReference1.TPEduInfoTransferSoap.SendContinueEduAsync(TestWeb.ServiceReference1.SendContinueEduRequest request) {
            return base.Channel.SendContinueEduAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWeb.ServiceReference1.SendContinueEduResponse> SendContinueEduAsync(string XTID, string JYXX) {
            TestWeb.ServiceReference1.SendContinueEduRequest inValue = new TestWeb.ServiceReference1.SendContinueEduRequest();
            inValue.Body = new TestWeb.ServiceReference1.SendContinueEduRequestBody();
            inValue.Body.XTID = XTID;
            inValue.Body.JYXX = JYXX;
            return ((TestWeb.ServiceReference1.TPEduInfoTransferSoap)(this)).SendContinueEduAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWeb.ServiceReference1.DetailsBrowerResponse TestWeb.ServiceReference1.TPEduInfoTransferSoap.DetailsBrower(TestWeb.ServiceReference1.DetailsBrowerRequest request) {
            return base.Channel.DetailsBrower(request);
        }
        
        public string DetailsBrower(string fkey, string StrWebUrl, out string OUTINFO) {
            TestWeb.ServiceReference1.DetailsBrowerRequest inValue = new TestWeb.ServiceReference1.DetailsBrowerRequest();
            inValue.Body = new TestWeb.ServiceReference1.DetailsBrowerRequestBody();
            inValue.Body.fkey = fkey;
            inValue.Body.StrWebUrl = StrWebUrl;
            TestWeb.ServiceReference1.DetailsBrowerResponse retVal = ((TestWeb.ServiceReference1.TPEduInfoTransferSoap)(this)).DetailsBrower(inValue);
            OUTINFO = retVal.Body.OUTINFO;
            return retVal.Body.DetailsBrowerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWeb.ServiceReference1.DetailsBrowerResponse> TestWeb.ServiceReference1.TPEduInfoTransferSoap.DetailsBrowerAsync(TestWeb.ServiceReference1.DetailsBrowerRequest request) {
            return base.Channel.DetailsBrowerAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWeb.ServiceReference1.DetailsBrowerResponse> DetailsBrowerAsync(string fkey, string StrWebUrl) {
            TestWeb.ServiceReference1.DetailsBrowerRequest inValue = new TestWeb.ServiceReference1.DetailsBrowerRequest();
            inValue.Body = new TestWeb.ServiceReference1.DetailsBrowerRequestBody();
            inValue.Body.fkey = fkey;
            inValue.Body.StrWebUrl = StrWebUrl;
            return ((TestWeb.ServiceReference1.TPEduInfoTransferSoap)(this)).DetailsBrowerAsync(inValue);
        }
    }
}
