//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestInter.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.StartSoap")]
    public interface StartSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetailBrowser", ReplyAction="*")]
        TestInter.ServiceReference1.DetailBrowserResponse DetailBrowser(TestInter.ServiceReference1.DetailBrowserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetailBrowser", ReplyAction="*")]
        System.Threading.Tasks.Task<TestInter.ServiceReference1.DetailBrowserResponse> DetailBrowserAsync(TestInter.ServiceReference1.DetailBrowserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DetailBrowserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DetailBrowser", Namespace="http://tempuri.org/", Order=0)]
        public TestInter.ServiceReference1.DetailBrowserRequestBody Body;
        
        public DetailBrowserRequest() {
        }
        
        public DetailBrowserRequest(TestInter.ServiceReference1.DetailBrowserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DetailBrowserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XTID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FKEY;
        
        public DetailBrowserRequestBody() {
        }
        
        public DetailBrowserRequestBody(string XTID, string FKEY) {
            this.XTID = XTID;
            this.FKEY = FKEY;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DetailBrowserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DetailBrowserResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestInter.ServiceReference1.DetailBrowserResponseBody Body;
        
        public DetailBrowserResponse() {
        }
        
        public DetailBrowserResponse(TestInter.ServiceReference1.DetailBrowserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DetailBrowserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DetailBrowserResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string info;
        
        public DetailBrowserResponseBody() {
        }
        
        public DetailBrowserResponseBody(string DetailBrowserResult, string info) {
            this.DetailBrowserResult = DetailBrowserResult;
            this.info = info;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StartSoapChannel : TestInter.ServiceReference1.StartSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StartSoapClient : System.ServiceModel.ClientBase<TestInter.ServiceReference1.StartSoap>, TestInter.ServiceReference1.StartSoap {
        
        public StartSoapClient() {
        }
        
        public StartSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StartSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StartSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StartSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestInter.ServiceReference1.DetailBrowserResponse TestInter.ServiceReference1.StartSoap.DetailBrowser(TestInter.ServiceReference1.DetailBrowserRequest request) {
            return base.Channel.DetailBrowser(request);
        }
        
        public string DetailBrowser(string XTID, string FKEY, out string info) {
            TestInter.ServiceReference1.DetailBrowserRequest inValue = new TestInter.ServiceReference1.DetailBrowserRequest();
            inValue.Body = new TestInter.ServiceReference1.DetailBrowserRequestBody();
            inValue.Body.XTID = XTID;
            inValue.Body.FKEY = FKEY;
            TestInter.ServiceReference1.DetailBrowserResponse retVal = ((TestInter.ServiceReference1.StartSoap)(this)).DetailBrowser(inValue);
            info = retVal.Body.info;
            return retVal.Body.DetailBrowserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestInter.ServiceReference1.DetailBrowserResponse> TestInter.ServiceReference1.StartSoap.DetailBrowserAsync(TestInter.ServiceReference1.DetailBrowserRequest request) {
            return base.Channel.DetailBrowserAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestInter.ServiceReference1.DetailBrowserResponse> DetailBrowserAsync(string XTID, string FKEY) {
            TestInter.ServiceReference1.DetailBrowserRequest inValue = new TestInter.ServiceReference1.DetailBrowserRequest();
            inValue.Body = new TestInter.ServiceReference1.DetailBrowserRequestBody();
            inValue.Body.XTID = XTID;
            inValue.Body.FKEY = FKEY;
            return ((TestInter.ServiceReference1.StartSoap)(this)).DetailBrowserAsync(inValue);
        }
    }
}
